import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Box, Button, Grid, Typography } from "@mui/material";
import {
  Bar,
  BarChart,
  Cell,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip as RechartTooltip,
  XAxis,
} from "recharts";
import { MapContainer, Polygon, TileLayer, Tooltip } from "react-leaflet";
import Skeleton from "react-loading-skeleton";

import { useDashboardData } from "./useDashboardData";
import { useAuth } from "../../context/AuthContext";
import { acknowledgeAlert, resolveAlert } from "../../api/alerts";
import {
  checkIn,
  checkOut,
  fetchHeadcount,
  fetchMyPresence,
  fetchRedAlertInside,
} from "../../api/presence";
import { formatTimeAgo } from "../../utils/formatUtils";

const UI = {
  surfaceLowest: "#0e0e0e",
  surface: "#131313",
  surfaceContainerLow: "#1c1b1b",
  surfaceContainer: "#201f1f",
  surfaceContainerHigh: "#2a2a2a",
  surfaceBright: "#3a3939",
  onSurface: "#e5e2e1",
  onSurfaceVariant: "#e4beba",
  outlineVariant: "#5b403e",
  primary: "#ffb3ad",
  primaryContainer: "#ff5451",
  secondary: "#ffb95f",
  secondaryContainer: "#ee9800",
  tertiary: "#4edea3",
  tertiaryContainer: "#00a572",
  onPrimary: "#68000a",
};

const RISK_COLORS = {
  red: UI.primaryContainer,
  orange: UI.secondaryContainer,
  yellow: UI.secondary,
  green: UI.tertiaryContainer,
};

const ANALYTICS_CARD_HEIGHT = 340;

function riskScorePct(zone) {
  const raw = Number(zone?.risk_score ?? 0);
  if (Number.isFinite(raw) && raw > 0) {
    if (raw <= 1) return Math.round(raw * 100);
    return Math.max(0, Math.min(100, Math.round(raw)));
  }

  if (zone?.risk_level === "red") return 94;
  if (zone?.risk_level === "orange") return 72;
  if (zone?.risk_level === "yellow") return 68;
  return 14;
}

function cardBase(extra = {}) {
  return {
    background: UI.surfaceContainer,
    border: `1px solid rgba(91,64,62,0.15)`,
    borderRadius: "10px",
    ...extra,
  };
}

function revealSx(delay = 0) {
  return {
    animation: `revealUp 480ms ease ${delay}ms both`,
    "@keyframes revealUp": {
      "0%": { opacity: 0, transform: "translateY(8px)" },
      "100%": { opacity: 1, transform: "translateY(0)" },
    },
  };
}

function KpiCard({ title, value, color, leftBorderColor, icon, pulse }) {
  return (
    <Box sx={cardBase({ p: 2.2, borderLeft: `2px solid ${leftBorderColor}` })}>
      <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
        <Box>
          <Typography sx={{ fontSize: "0.6875rem", fontWeight: 300, letterSpacing: "0.08em", textTransform: "uppercase", color: UI.onSurfaceVariant, mb: 0.6 }}>
            {title}
          </Typography>
          <Typography sx={{ fontSize: 34, lineHeight: 1, fontWeight: 800, color }}>
            {value}
          </Typography>
        </Box>
        {icon ? (
          <Box
            sx={{
              color,
              p: 0.6,
              borderRadius: "999px",
              boxShadow: pulse ? `0 0 12px ${UI.primaryContainer}` : "none",
              animation: pulse ? "pulseWarn 1.5s infinite" : "none",
              "@keyframes pulseWarn": {
                "0%": { opacity: 1, transform: "scale(1)" },
                "50%": { opacity: 0.6, transform: "scale(1.05)" },
                "100%": { opacity: 1, transform: "scale(1)" },
              },
            }}
          >
            <span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 1", fontSize: 22 }}>
              {icon}
            </span>
          </Box>
        ) : null}
      </Box>
    </Box>
  );
}

function AlertItem({ alert, canAct, onAck, onResolve }) {
  const color = RISK_COLORS[alert?.risk_level] || UI.secondaryContainer;

  return (
    <Box sx={{ background: UI.surfaceContainerLow, p: 1.8, borderRadius: "4px", borderLeft: `4px solid ${color}` }}>
      <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", mb: 1 }}>
        <Typography sx={{ fontSize: "0.6rem", fontWeight: 700, textTransform: "uppercase", color }}>
          {alert?.risk_level === "red" ? "Extreme Alert" : "Caution"}
        </Typography>
        <Typography sx={{ fontSize: "0.6rem", color: UI.onSurfaceVariant }}>
          {formatTimeAgo(alert?.created_at)}
        </Typography>
      </Box>

      <Typography sx={{ fontSize: "0.78rem", fontWeight: 700, color: UI.onSurface, mb: 0.4 }}>
        {alert?.zone_name || "Unknown Zone"}
      </Typography>

      <Typography sx={{ fontSize: "0.65rem", color: UI.onSurfaceVariant, lineHeight: 1.55, mb: 1.3 }}>
        {(alert?.trigger_reason || "Alert generated by safety engine.").slice(0, 125)}
      </Typography>

      {canAct && alert?.status === "active" ? (
        <Box sx={{ display: "flex", gap: 1 }}>
          <Button
            onClick={() => onAck(alert.id)}
            fullWidth
            size="small"
            sx={{
              bgcolor: UI.primaryContainer,
              color: UI.onPrimary,
              borderRadius: "4px",
              textTransform: "uppercase",
              fontWeight: 800,
              fontSize: "0.6rem",
              py: 0.55,
              "&:hover": { bgcolor: "#ff6b66" },
            }}
          >
            Acknowledge
          </Button>
          <Button
            onClick={() => onResolve(alert.id)}
            fullWidth
            size="small"
            sx={{
              border: `1px solid ${UI.outlineVariant}`,
              color: UI.onSurface,
              borderRadius: "4px",
              textTransform: "uppercase",
              fontWeight: 800,
              fontSize: "0.6rem",
              py: 0.55,
              "&:hover": { bgcolor: UI.surfaceContainerHigh },
            }}
          >
            Resolve
          </Button>
        </Box>
      ) : (
        <Button
          fullWidth
          size="small"
          sx={{
            border: `1px solid ${UI.outlineVariant}`,
            color: UI.onSurface,
            borderRadius: "4px",
            textTransform: "uppercase",
            fontWeight: 800,
            fontSize: "0.6rem",
            py: 0.55,
            "&:hover": { bgcolor: UI.surfaceContainerHigh },
          }}
        >
          Acknowledge
        </Button>
      )}
    </Box>
  );
}

function WorkforceRow({ row, onCheckOut, disabled }) {
  const dotColor = row.inside_count > 30 ? UI.tertiary : row.inside_count > 10 ? UI.secondaryContainer : UI.primaryContainer;
  return (
    <Box sx={{
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      p: 1,
      borderRadius: "4px",
      transition: "background 0.25s",
      "&:hover": { bgcolor: UI.surfaceContainer },
    }}>
      <Box sx={{ display: "flex", alignItems: "center", gap: 1.2 }}>
        <Box sx={{ width: 8, height: 8, borderRadius: "999px", bgcolor: dotColor }} />
        <Box>
          <Typography sx={{ fontSize: "0.76rem", fontWeight: 700, color: UI.onSurface }}>
            {row.zone_name}
          </Typography>
          <Typography sx={{ fontSize: "0.6rem", color: UI.onSurfaceVariant }}>
            {row.inside_count} Personnel
          </Typography>
        </Box>
      </Box>

      <Button
        onClick={onCheckOut}
        disabled={disabled}
        size="small"
        sx={{
          fontSize: "0.55rem",
          fontWeight: 800,
          px: 1.1,
          py: 0.3,
          border: `1px solid ${UI.outlineVariant}`,
          color: UI.onSurfaceVariant,
          borderRadius: "4px",
          textTransform: "uppercase",
          minWidth: 0,
          "&:hover": { color: UI.primaryContainer, borderColor: UI.primaryContainer },
        }}
      >
        Check Out
      </Button>
    </Box>
  );
}

export default function DashboardPage() {
  const navigate = useNavigate();
  const { currentUser } = useAuth();
  const canAct = ["admin", "safety_officer"].includes(currentUser?.role);
  const isFieldWorker = currentUser?.role === "field_worker";

  const [headcountRows, setHeadcountRows] = useState([]);
  const [redInsideRows, setRedInsideRows] = useState([]);
  const [myPresence, setMyPresence] = useState(null);
  const [presenceBusy, setPresenceBusy] = useState(false);

  const {
    zones,
    kpis,
    recentAlerts,
    distribution,
    trendData,
    rainfallSummary,
    activityFeed,
    loading,
  } = useDashboardData();

  const loadPresence = useCallback(async () => {
    try {
      const [headcount, redInside] = await Promise.all([
        fetchHeadcount(),
        fetchRedAlertInside(),
      ]);

      setHeadcountRows(headcount?.zones || []);
      setRedInsideRows(redInside?.zones || []);

      if (isFieldWorker) {
        const mine = await fetchMyPresence();
        setMyPresence(mine || null);
      }
    } catch {
      setHeadcountRows([]);
      setRedInsideRows([]);
      setMyPresence(null);
    }
  }, [isFieldWorker]);

  useEffect(() => {
    loadPresence();
    const timer = setInterval(loadPresence, 12000);
    return () => clearInterval(timer);
  }, [loadPresence]);

  const handleAck = async (id) => {
    await acknowledgeAlert(id);
  };

  const handleResolve = async (id) => {
    await resolveAlert(id);
  };

  const handleCheckOut = async () => {
    if (!isFieldWorker) return;
    setPresenceBusy(true);
    try {
      await checkOut();
      await loadPresence();
    } finally {
      setPresenceBusy(false);
    }
  };

  const handleCheckIn = async () => {
    if (!isFieldWorker) return;
    setPresenceBusy(true);
    try {
      await checkIn(currentUser?.zone_assigned || undefined);
      await loadPresence();
    } finally {
      setPresenceBusy(false);
    }
  };

  const mapCenter = [19.7515, 75.7139];

  const donutData = [
    { name: "Critical", value: distribution?.red || 0, color: UI.primaryContainer },
    { name: "Caution", value: distribution?.orange || 0, color: UI.secondaryContainer },
    { name: "Stable", value: distribution?.green || 0, color: UI.tertiaryContainer },
  ];

  const totalZones = donutData.reduce((sum, row) => sum + row.value, 0) || (zones?.length || 0);

  const redOccupants = useMemo(() => {
    return (redInsideRows || [])
      .flatMap((zone) => (zone.inside_workers || []).map((worker) => ({
        name: worker.user_name || "Unknown",
        zoneName: zone.zone_name,
      })))
      .slice(0, 4);
  }, [redInsideRows]);

  const rankedZones = useMemo(() => {
    return (zones || [])
      .map((zone) => ({ ...zone, score: riskScorePct(zone) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, 4);
  }, [zones]);

  if (loading) {
    return (
      <Box sx={{ display: "grid", gap: 2.2 }}>
        <Skeleton height={80} />
        <Grid container spacing={2}>
          {[1, 2, 3, 4].map((i) => (
            <Grid item xs={12} md={3} key={i}>
              <Skeleton height={100} />
            </Grid>
          ))}
        </Grid>
        <Skeleton height={460} />
        <Skeleton height={320} />
      </Box>
    );
  }

  return (
    <Box>

      <Grid container spacing={2} sx={{ mb: 2.4 }}>
        <Grid item xs={12} md={3} sx={revealSx(10)}>
          <KpiCard
            title="Total Monitored Zones"
            value={kpis?.totalZones ?? 0}
            color={UI.onSurface}
            leftBorderColor="rgba(255,179,173,0.4)"
          />
        </Grid>
        <Grid item xs={12} md={3} sx={revealSx(55)}>
          <KpiCard
            title="Critical Zones"
            value={kpis?.criticalZones ?? 0}
            color={UI.primaryContainer}
            leftBorderColor={UI.primaryContainer}
            icon="warning"
            pulse
          />
        </Grid>
        <Grid item xs={12} md={3} sx={revealSx(100)}>
          <KpiCard
            title="Active Alerts"
            value={kpis?.activeAlerts ?? 0}
            color={UI.secondary}
            leftBorderColor={UI.secondary}
          />
        </Grid>
        <Grid item xs={12} md={3} sx={revealSx(145)}>
          <KpiCard
            title="Reports Today"
            value={kpis?.reportsToday ?? 0}
            color={UI.tertiary}
            leftBorderColor={UI.tertiary}
          />
        </Grid>
      </Grid>

      <Grid container spacing={2.4} sx={{ mb: 2.4 }}>
        <Grid item xs={12} lg={8} sx={revealSx(70)}>
          <Box sx={cardBase({
            background: UI.surfaceContainerHigh,
            minHeight: 480,
            overflow: "hidden",
            position: "relative",
          })}>
            <Box sx={{
              position: "absolute",
              top: 16,
              left: 16,
              zIndex: 1000,
              p: 1.6,
              borderRadius: "8px",
              border: `1px solid rgba(91,64,62,0.2)`,
              background: "rgba(42, 42, 42, 0.4)",
              backdropFilter: "blur(20px)",
            }}>
              <Typography sx={{ fontSize: "0.85rem", fontWeight: 700, color: UI.onSurface, mb: 1.2 }}>
                Mine Risk Map
              </Typography>
              <Box sx={{ display: "grid", gap: 0.8 }}>
                {["Extreme Risk", "High Caution", "Stable"].map((label, idx) => {
                  const color = idx === 0 ? UI.primaryContainer : idx === 1 ? UI.secondaryContainer : UI.tertiaryContainer;
                  return (
                    <Box key={label} sx={{ display: "flex", alignItems: "center", gap: 0.9 }}>
                      <Box sx={{ width: 10, height: 10, borderRadius: "50%", bgcolor: color }} />
                      <Typography sx={{ fontSize: "0.65rem", color: UI.onSurfaceVariant, textTransform: "uppercase", letterSpacing: "0.12em" }}>
                        {label}
                      </Typography>
                    </Box>
                  );
                })}
              </Box>
            </Box>

            <Box sx={{ width: "100%", height: 480, background: UI.surfaceLowest }}>
              <MapContainer center={mapCenter} zoom={6} style={{ width: "100%", height: "100%" }} zoomControl={false}>
                <TileLayer
                  url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"
                  attribution="&copy; CartoDB"
                />
                {(zones || []).map((zone) => zone?.latlngs?.length > 0 ? (
                  <Polygon
                    key={zone.id}
                    positions={zone.latlngs}
                    pathOptions={{
                      fillColor: RISK_COLORS[zone.risk_level] || UI.tertiaryContainer,
                      fillOpacity: 0.38,
                      color: RISK_COLORS[zone.risk_level] || UI.tertiaryContainer,
                      weight: 1.5,
                    }}
                    eventHandlers={{ click: () => navigate(`/zones/${zone.id}`) }}
                  >
                    <Tooltip sticky>
                      <Box sx={{ fontSize: 11, color: UI.onSurface }}>
                        {zone.name} - {(zone.risk_level || "green").toUpperCase()}
                      </Box>
                    </Tooltip>
                  </Polygon>
                ) : null)}
              </MapContainer>
            </Box>
          </Box>
        </Grid>

        <Grid item xs={12} lg={4} sx={revealSx(120)}>
          <Box sx={cardBase({ background: UI.surfaceContainerHigh, height: 480, display: "flex", flexDirection: "column", overflow: "hidden" })}>
            <Box sx={{ p: 1.8, borderBottom: `1px solid rgba(91,64,62,0.1)`, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <Typography sx={{ fontSize: "0.78rem", fontWeight: 700, color: UI.onSurface, textTransform: "uppercase", letterSpacing: "0.1em" }}>
                Active Alerts
              </Typography>
              <Typography sx={{ fontSize: "0.65rem", fontWeight: 800, color: UI.primaryContainer }}>
                REAL-TIME FEED
              </Typography>
            </Box>

            <Box sx={{
              flex: 1,
              overflowY: "auto",
              p: 1.8,
              display: "grid",
              gap: 1.4,
              "&::-webkit-scrollbar": { width: 4 },
              "&::-webkit-scrollbar-track": { background: UI.surfaceLowest },
              "&::-webkit-scrollbar-thumb": { background: UI.surfaceBright },
            }}>
              {(recentAlerts || []).length === 0 ? (
                <Typography sx={{ fontSize: "0.72rem", color: UI.onSurfaceVariant }}>
                  No active alerts.
                </Typography>
              ) : (
                (recentAlerts || []).slice(0, 8).map((alert) => (
                  <AlertItem
                    key={alert.id}
                    alert={alert}
                    canAct={canAct}
                    onAck={handleAck}
                    onResolve={handleResolve}
                  />
                ))
              )}
            </Box>
          </Box>
        </Grid>
      </Grid>

      <Grid container spacing={2.4} sx={{ mb: 2.4, alignItems: "stretch" }}>
        <Grid item xs={12} md={4} sx={{ display: "flex", ...revealSx(60) }}>
          <Box sx={cardBase({ background: UI.surfaceContainerHigh, p: 2.2, width: "100%", height: ANALYTICS_CARD_HEIGHT })}>
            <Typography sx={{ fontSize: "0.74rem", fontWeight: 700, color: UI.onSurfaceVariant, textTransform: "uppercase", letterSpacing: "0.14em", mb: 1.8 }}>
              Risk Distribution
            </Typography>

            <Box sx={{ position: "relative", height: 150 }}>
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={donutData}
                    dataKey="value"
                    cx="50%"
                    cy="50%"
                    innerRadius={40}
                    outerRadius={58}
                    startAngle={90}
                    endAngle={-270}
                    paddingAngle={3}
                  >
                    {donutData.map((entry) => (
                      <Cell key={entry.name} fill={entry.color} />
                    ))}
                  </Pie>
                </PieChart>
              </ResponsiveContainer>

              <Box sx={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", pointerEvents: "none" }}>
                <Typography sx={{ fontSize: 24, fontWeight: 800, color: UI.onSurface }}>
                  {totalZones}
                </Typography>
                <Typography sx={{ fontSize: "0.5rem", color: UI.onSurfaceVariant, textTransform: "uppercase", letterSpacing: "0.11em" }}>
                  Total Zones
                </Typography>
              </Box>
            </Box>

            <Grid container spacing={1} sx={{ mt: 1.2 }}>
              <Grid item xs={6}>
                <Box sx={{ textAlign: "center" }}>
                  <Typography sx={{ fontSize: "0.6rem", color: UI.onSurfaceVariant, textTransform: "uppercase" }}>
                    Critical
                  </Typography>
                  <Typography sx={{ fontSize: "0.95rem", fontWeight: 800, color: UI.primary }}>
                    {totalZones ? `${Math.round(((distribution?.red || 0) / totalZones) * 100)}%` : "0%"}
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={6}>
                <Box sx={{ textAlign: "center" }}>
                  <Typography sx={{ fontSize: "0.6rem", color: UI.onSurfaceVariant, textTransform: "uppercase" }}>
                    Stable
                  </Typography>
                  <Typography sx={{ fontSize: "0.95rem", fontWeight: 800, color: UI.tertiary }}>
                    {totalZones ? `${Math.round(((distribution?.green || 0) / totalZones) * 100)}%` : "0%"}
                  </Typography>
                </Box>
              </Grid>
            </Grid>
          </Box>
        </Grid>

        <Grid item xs={12} md={4} sx={{ display: "flex", ...revealSx(100) }}>
          <Box sx={cardBase({ background: UI.surfaceContainerHigh, p: 2.2, width: "100%", height: ANALYTICS_CARD_HEIGHT })}>
            <Typography sx={{ fontSize: "0.74rem", fontWeight: 700, color: UI.onSurfaceVariant, textTransform: "uppercase", letterSpacing: "0.14em", mb: 1.8 }}>
              7-Day Risk Trend
            </Typography>

            <Box sx={{ height: 180 }}>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={trendData || []} barCategoryGap="24%">
                  <XAxis
                    dataKey="day"
                    tick={{ fill: UI.onSurfaceVariant, fontSize: 9 }}
                    axisLine={false}
                    tickLine={false}
                  />
                  <RechartTooltip
                    contentStyle={{
                      background: UI.surfaceContainer,
                      border: `1px solid rgba(91,64,62,0.2)`,
                      borderRadius: 4,
                      color: UI.onSurface,
                      fontSize: 11,
                    }}
                    cursor={{ fill: "rgba(255,84,81,0.08)" }}
                  />
                  <Bar dataKey="red" fill={UI.primaryContainer} radius={[2, 2, 0, 0]} />
                  <Bar dataKey="orange" fill={UI.secondaryContainer} radius={[2, 2, 0, 0]} />
                  <Bar dataKey="yellow" fill="rgba(91,64,62,0.2)" radius={[2, 2, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </Box>
          </Box>
        </Grid>

        <Grid item xs={12} md={4} sx={{ display: "flex", ...revealSx(140) }}>
          <Box sx={cardBase({ background: UI.surfaceContainerHigh, p: 2.2, width: "100%", height: ANALYTICS_CARD_HEIGHT, display: "flex", flexDirection: "column", justifyContent: "space-between" })}>
            <Box>
              <Typography sx={{ fontSize: "0.74rem", fontWeight: 700, color: UI.onSurfaceVariant, textTransform: "uppercase", letterSpacing: "0.14em", mb: 0.2 }}>
                Rainfall Snapshot
              </Typography>
              <Typography sx={{ fontSize: "0.65rem", color: UI.tertiaryContainer, fontWeight: 800 }}>
                REGION: {rainfallSummary?.district?.toUpperCase() || "NORTHERN PLATEAU"}
              </Typography>
            </Box>

            <Box sx={{ display: "flex", alignItems: "center", gap: 1.8, mt: 1.4 }}>
              <span className="material-symbols-outlined" style={{ fontSize: 38, color: "#60a5fa" }}>rainy</span>
              <Box>
                <Typography sx={{ fontSize: 34, lineHeight: 1, fontWeight: 800, color: UI.onSurface }}>
                  {Number(rainfallSummary?.rainfallLast24h || 0).toFixed(1)}
                  <span style={{ fontSize: "0.85rem", fontWeight: 400, color: UI.onSurfaceVariant, marginLeft: 6 }}>mm</span>
                </Typography>
                <Typography sx={{ fontSize: "0.62rem", color: UI.secondary, fontWeight: 800, textTransform: "uppercase" }}>
                  {rainfallSummary?.trend === "rising" ? "+12% vs Average" : "Within seasonal range"}
                </Typography>
              </Box>
            </Box>

            <Box sx={{ mt: 1.3, pt: 1.4, borderTop: `1px solid rgba(91,64,62,0.1)` }}>
              <Box sx={{ display: "flex", justifyContent: "space-between" }}>
                <Typography sx={{ fontSize: "0.65rem", color: UI.onSurfaceVariant, textTransform: "uppercase" }}>
                  Saturation Level
                </Typography>
                <Typography sx={{ fontSize: "0.65rem", color: UI.onSurface, fontWeight: 700 }}>
                  {Math.min(100, Math.round(Number(rainfallSummary?.rainfallLast7d || 0)))}%
                </Typography>
              </Box>
              <Box sx={{ width: "100%", height: 4, bgcolor: UI.surfaceContainer, mt: 0.7, borderRadius: "999px", overflow: "hidden" }}>
                <Box
                  sx={{
                    width: `${Math.min(100, Math.round(Number(rainfallSummary?.rainfallLast7d || 0)))}%`,
                    height: "100%",
                    bgcolor: UI.secondary,
                  }}
                />
              </Box>
            </Box>
          </Box>
        </Grid>
      </Grid>

      <Grid container spacing={2.4} sx={{ mb: 2.4 }}>
        <Grid item xs={12} lg={4} sx={revealSx(80)}>
          <Box sx={cardBase({ background: UI.surfaceContainerHigh, borderRadius: "10px", overflow: "hidden", display: "flex", flexDirection: "column", minHeight: 330 })}>
            <Box sx={{ p: 1.8, borderBottom: `1px solid rgba(91,64,62,0.1)`, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <Typography sx={{ fontSize: "0.74rem", fontWeight: 700, color: UI.onSurface, textTransform: "uppercase", letterSpacing: "0.1em" }}>
                Workforce Presence
              </Typography>
              <Typography sx={{ fontSize: "0.65rem", fontWeight: 800, color: UI.tertiary }}>
                {(headcountRows || []).reduce((sum, row) => sum + Number(row.inside_count || 0), 0)} ACTIVE
              </Typography>
            </Box>

            <Box sx={{
              flex: 1,
              overflowY: "auto",
              p: 1.6,
              display: "grid",
              gap: 0.7,
              "&::-webkit-scrollbar": { width: 4 },
              "&::-webkit-scrollbar-track": { background: UI.surfaceLowest },
              "&::-webkit-scrollbar-thumb": { background: UI.surfaceBright },
            }}>
              {(headcountRows || []).slice(0, 6).map((row) => (
                <WorkforceRow
                  key={row.zone_id}
                  row={row}
                  onCheckOut={handleCheckOut}
                  disabled={presenceBusy || !isFieldWorker}
                />
              ))}

              {isFieldWorker ? (
                <Box sx={{ display: "flex", gap: 1, pt: 1 }}>
                  <Button
                    onClick={handleCheckIn}
                    disabled={presenceBusy}
                    fullWidth
                    size="small"
                    sx={{
                      fontSize: "0.58rem",
                      fontWeight: 800,
                      textTransform: "uppercase",
                      color: UI.onPrimary,
                      bgcolor: UI.secondary,
                      borderRadius: "4px",
                      "&:hover": { bgcolor: "#ffc879" },
                    }}
                  >
                    Check In ({myPresence?.status || "outside"})
                  </Button>
                </Box>
              ) : null}
            </Box>
          </Box>
        </Grid>

        <Grid item xs={12} lg={4} sx={revealSx(120)}>
          <Box sx={cardBase({
            background: UI.surfaceContainerHigh,
            borderRadius: "10px",
            overflow: "hidden",
            minHeight: 330,
            border: `1px solid rgba(255,84,81,0.2)`,
          })}>
            <Box sx={{
              p: 1.8,
              bgcolor: "rgba(255,84,81,0.1)",
              borderBottom: `1px solid rgba(255,84,81,0.2)`,
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}>
              <Typography sx={{ fontSize: "0.74rem", fontWeight: 700, color: UI.primary, textTransform: "uppercase", letterSpacing: "0.1em" }}>
                Red Alert Occupancy
              </Typography>
              <Typography sx={{
                fontSize: "0.65rem",
                fontWeight: 800,
                color: UI.primary,
                px: 1,
                boxShadow: `0 0 12px ${UI.primaryContainer}`,
                animation: "pulseDanger 1.5s infinite",
                "@keyframes pulseDanger": {
                  "0%": { opacity: 1, transform: "scale(1)" },
                  "50%": { opacity: 0.6, transform: "scale(1.05)" },
                  "100%": { opacity: 1, transform: "scale(1)" },
                },
              }}>
                DANGER
              </Typography>
            </Box>

            <Box sx={{ p: 1.8, display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 1 }}>
              {redOccupants.map((person) => {
                const initials = person.name
                  .split(" ")
                  .filter(Boolean)
                  .slice(0, 2)
                  .map((p) => p[0].toUpperCase())
                  .join("");

                return (
                  <Box key={`${person.name}-${person.zoneName}`} sx={{
                    p: 1,
                    borderRadius: "4px",
                    bgcolor: UI.surfaceContainerLow,
                    display: "flex",
                    alignItems: "center",
                    gap: 1,
                    border: `1px solid rgba(255,84,81,0.12)`,
                  }}>
                    <Box sx={{ width: 24, height: 24, borderRadius: "4px", bgcolor: "rgba(255,84,81,0.2)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "0.6rem", fontWeight: 800, color: UI.primary }}>
                      {initials || "NA"}
                    </Box>
                    <Typography sx={{ fontSize: "0.65rem", fontWeight: 700, color: UI.onSurface }}>
                      {person.name}
                    </Typography>
                  </Box>
                );
              })}

              {!redOccupants.length ? (
                <Typography sx={{ gridColumn: "1 / -1", fontSize: "0.65rem", color: UI.onSurfaceVariant }}>
                  No workers currently inside red-alert zones.
                </Typography>
              ) : null}
            </Box>

            <Box sx={{ mt: "auto", p: 1.8, bgcolor: "rgba(255,84,81,0.05)" }}>
              <Typography sx={{ fontSize: "0.6rem", color: UI.onSurfaceVariant, lineHeight: 1.45 }}>
                Occupants are in high-displacement zones. Evacuation signal has been transmitted.
              </Typography>
            </Box>
          </Box>
        </Grid>

        <Grid item xs={12} lg={4} sx={revealSx(160)}>
          <Box sx={cardBase({ background: UI.surfaceContainerHigh, borderRadius: "10px", overflow: "hidden", minHeight: 330, display: "flex", flexDirection: "column" })}>
            <Box sx={{ p: 1.8, borderBottom: `1px solid rgba(91,64,62,0.1)` }}>
              <Typography sx={{ fontSize: "0.74rem", fontWeight: 700, color: UI.onSurface, textTransform: "uppercase", letterSpacing: "0.1em" }}>
                Activity Timeline
              </Typography>
            </Box>

            <Box sx={{
              flex: 1,
              overflowY: "auto",
              p: 1.8,
              display: "grid",
              gap: 2.5,
              "&::-webkit-scrollbar": { width: 4 },
              "&::-webkit-scrollbar-track": { background: UI.surfaceLowest },
              "&::-webkit-scrollbar-thumb": { background: UI.surfaceBright },
            }}>
              {(activityFeed || []).slice(0, 6).map((item, idx) => {
                const dotColor = idx % 3 === 0 ? UI.secondary : idx % 3 === 1 ? UI.tertiary : UI.primary;
                return (
                  <Box key={`${item.title}-${idx}`} sx={{ position: "relative", pl: 2.6, borderLeft: `1px solid rgba(91,64,62,0.3)` }}>
                    <Box sx={{ position: "absolute", left: -6, top: 0, width: 12, height: 12, borderRadius: "50%", bgcolor: dotColor }} />
                    <Typography sx={{ fontSize: "0.6rem", color: UI.onSurfaceVariant, fontWeight: 700, mb: 0.4 }}>
                      {formatTimeAgo(item.time)}
                    </Typography>
                    <Typography sx={{ fontSize: "0.75rem", fontWeight: 700, color: UI.onSurface }}>
                      {item.title}
                    </Typography>
                    <Typography sx={{ fontSize: "0.65rem", color: UI.onSurfaceVariant }}>
                      {item.subtitle}
                    </Typography>
                  </Box>
                );
              })}

              {!activityFeed?.length ? (
                <Typography sx={{ fontSize: "0.65rem", color: UI.onSurfaceVariant }}>
                  No timeline events available.
                </Typography>
              ) : null}
            </Box>
          </Box>
        </Grid>
      </Grid>

      <Box sx={cardBase({
        background: UI.surfaceContainerHigh,
        borderRadius: "10px",
        overflow: "hidden",
        border: `1px solid rgba(91,64,62,0.1)`,
        ...revealSx(180),
      })}>
        <Box sx={{ p: 1.8, borderBottom: `1px solid rgba(91,64,62,0.1)` }}>
          <Typography sx={{ fontSize: "0.74rem", fontWeight: 700, color: UI.onSurface, textTransform: "uppercase", letterSpacing: "0.1em" }}>
            Zone Risk Ranking
          </Typography>
        </Box>

        <Box sx={{ p: 2.4 }}>
          <Grid container spacing={2.2}>
            {rankedZones.map((zone) => {
              const color = zone.score >= 85 ? UI.primaryContainer : zone.score >= 60 ? UI.secondaryContainer : UI.tertiaryContainer;
              return (
                <Grid key={zone.id} item xs={12} md={6}>
                  <Box onClick={() => navigate(`/zones/${zone.id}`)} sx={{ cursor: "pointer" }}>
                    <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", mb: 0.7 }}>
                      <Typography sx={{ fontSize: "0.7rem", fontWeight: 700, color: UI.onSurface }}>
                        {zone.name}
                      </Typography>
                      <Typography sx={{ fontSize: "0.7rem", fontWeight: 700, color }}>
                        {zone.score} / 100 Risk Score
                      </Typography>
                    </Box>
                    <Box sx={{ width: "100%", height: 8, borderRadius: "999px", bgcolor: UI.surfaceContainer, overflow: "hidden" }}>
                      <Box sx={{ width: `${zone.score}%`, height: "100%", bgcolor: color }} />
                    </Box>
                  </Box>
                </Grid>
              );
            })}

            {!rankedZones.length ? (
              <Grid item xs={12}>
                <Typography sx={{ fontSize: "0.7rem", color: UI.onSurfaceVariant }}>
                  No zones available.
                </Typography>
              </Grid>
            ) : null}
          </Grid>
        </Box>
      </Box>
    </Box>
  );
}
